#!/usr/bin/env python3
"""ORION Release Report Generator — auto-generates RELEASE_REPORT.md.

Usage:
    python scripts/generate_release_report.py                    # Read build/ and dist/
    python scripts/generate_release_report.py --build-dir PATH   # Custom build dir
    python scripts/generate_release_report.py --ci               # JSON output

This script reads:
  - build/release/build_info.json (auto-generated by build_release.py)
  - dist/Orion/ (asset tree)
  - stdout/stderr logs from test runs (optional)
  - Git log for changelog entries
"""

from __future__ import annotations

import argparse
import json
import subprocess
import sys
from datetime import datetime, timezone
from pathlib import Path

SCRIPT_DIR = Path(__file__).resolve().parent
PROJECT_ROOT = SCRIPT_DIR.parent
RELEASE_DIR = PROJECT_ROOT / "build" / "release"
DIST_DIR = PROJECT_ROOT / "dist"
REPORT_PATH = PROJECT_ROOT / "RELEASE_REPORT.md"


def run(cmd: list[str], timeout: int = 15) -> str:
    try:
        result = subprocess.run(cmd, capture_output=True, text=True, timeout=timeout, cwd=PROJECT_ROOT)
        return result.stdout.strip()
    except Exception:
        return "N/A"


def get_git_log() -> list[str]:
    out = run(["git", "log", "--oneline", "-20"])
    return out.split("\n") if out != "N/A" else []


def load_build_info(build_dir: Path) -> dict | None:
    candidates = [
        build_dir / "build_info.json",
        RELEASE_DIR / "build_info.json",
    ]
    for c in candidates:
        if c.exists():
            return json.loads(c.read_text())
    return None


def read_test_results() -> dict:
    results = {"smoke": "NOT RUN", "portable": "NOT RUN", "installer": "NOT RUN"}
    # Check for log files that test scripts might leave
    for test_name in ["smoke_test", "test_portable", "test_installer"]:
        log_file = PROJECT_ROOT / f"{test_name}.log"
        if log_file.exists():
            content = log_file.read_text()
            if "FAIL" in content or "FAILED" in content:
                results[test_name.replace("test_", "").replace("smoke_test", "smoke")] = "FAIL"
            elif "PASS" in content or "OK" in content or "✓" in content:
                results[test_name.replace("test_", "").replace("smoke_test", "smoke")] = "PASS"
            else:
                results[test_name.replace("test_", "").replace("smoke_test", "smoke")] = "UNKNOWN"
    return results


def format_files_table(files: dict) -> str:
    rows = []
    for name, info in sorted(files.items()):
        size = info.get("size_human", f"{info['size_bytes'] / 1024:.1f} KB")
        rows.append(f"  | {name} | {size} |")
    return "\n".join(rows)


def main() -> None:
    parser = argparse.ArgumentParser(description="ORION Release Report Generator")
    parser.add_argument("--build-dir", type=Path, default=None, help="Custom build directory")
    parser.add_argument("--ci", action="store_true", help="JSON output")
    parser.add_argument("--json", action="store_true", help="Output as JSON")
    args = parser.parse_args()

    build_dir = args.build_dir or RELEASE_DIR
    info = load_build_info(build_dir)

    version = info["version"] if info else run(["cat", "VERSION"])
    build_date = info["build_date"][:10] if info and "build_date" in info else datetime.now().strftime("%Y-%m-%d")
    commit = info.get("commit", "N/A") if info else run(["git", "rev-parse", "--short", "HEAD"])
    platform = info["platform"] if info and "platform" in info else sys.platform
    sha256_artifacts = info.get("sha256", {}) if info else {}
    total_size = info.get("total_size_human", "N/A") if info else "N/A"
    components = info.get("components", {}) if info else {}
    git_log = get_git_log()

    test_results = read_test_results()

    # Build a release summary
    hashes_section = ""
    if sha256_artifacts:
        hashes_section = "## SHA256 Checksums\n\n"
        for name, h in sorted(sha256_artifacts.items()):
            hashes_section += f"| {name} | `{h}` |\n"

    components_section = ""
    if components:
        components_section = "## Build Components\n\n"
        components_section += "| Component | Status |\n"
        components_section += "|-----------|--------|\n"
        for name, ok in components.items():
            status = "✓ PASS" if ok else "✗ FAIL / SKIP"
            components_section += f"| {name} | {status} |\n"

    test_section = ""
    for test_name, status in test_results.items():
        icon = "✓" if status == "PASS" else "✗" if status == "FAIL" else "—"
        test_section += f"| {test_name} | {icon} {status} |\n"

    changelog_section = ""
    if git_log:
        changelog_section = "## Recent Commits\n\n"
        for line in git_log[:15]:
            changelog_section += f"- {line}\n"

    report = f"""# ORION Release Report

## Summary

| Field | Value |
|-------|-------|
| **Application** | ORION |
| **Version** | v{version} |
| **Build ID** | `{info.get("build_id", f"v{version}-{build_date.replace('-','')}") if info else f"v{version}-{build_date.replace('-','')}"}` |
| **Build Date** | {build_date} |
| **Commit** | `{commit}` |
| **Platform** | {platform} |
| **Total Size** | {total_size} |

## Test Results

| Test | Status |
|------|--------|
{test_section}

{hashes_section}
{components_section}
## File Manifest

| File | Size |
|------|------|
{format_files_table(info["files"]) if info and "files" in info else "  (no file manifest available)"}

{changelog_section}
## Platform Requirements

- **Windows 11 64-bit** (recommended)
- 4 GB RAM (8 GB recommended)
- No Python, Node.js, or Git required for end users
- Double-click installation via OrionInstaller.exe

---

*Report auto-generated on {datetime.now(timezone.utc).strftime('%Y-%m-%d %H:%M:%S UTC')}*
"""

    REPORT_PATH.write_text(report)
    print(f"RELEASE_REPORT.md written to {REPORT_PATH}")
    print(f"  Version: v{version}")
    print(f"  Build:   {build_date}")
    print(f"  Commit:  {commit}")

    if args.json or args.ci:
        output = {
            "success": True,
            "version": version,
            "build_date": build_date,
            "commit": commit,
            "platform": platform,
            "total_size": total_size,
            "sha256": sha256_artifacts,
            "components": components,
            "test_results": test_results,
            "report_path": str(REPORT_PATH),
        }
        print(json.dumps(output, indent=2))


if __name__ == "__main__":
    main()
