from __future__ import annotations

import json
import logging
from datetime import datetime, timezone
from typing import Any

logger = logging.getLogger("rastro.export")

EXPORT_FORMATS = ["markdown", "html", "pdf", "txt"]


def _get_session():
    from database.db import SessionLocal
    return SessionLocal()


def _get_report(report_id: int) -> dict[str, Any] | None:
    from database.models import Report
    session = _get_session()
    try:
        r = session.query(Report).filter(Report.id == report_id).first()
        if not r:
            return None
        content = r.content or "{}"
        if isinstance(content, str):
            try:
                content = json.loads(content)
            except (json.JSONDecodeError, TypeError):
                content = {"raw": content[:500]}
        return {
            "id": r.id,
            "program": r.program or "",
            "target": r.target or "",
            "vulnerability": r.vulnerability or "",
            "severity": r.severity or "medium",
            "status": r.status or "draft",
            "content": content,
            "estimated_reward": r.estimated_reward or 0.0,
            "created_at": r.created_at.isoformat() if r.created_at else "",
        }
    finally:
        session.close()


def _render_markdown(report: dict[str, Any]) -> str:
    content = report.get("content", {})
    if isinstance(content, str):
        return content
    title = report.get("vulnerability", "Security Report")
    program = report.get("program", "Unknown Program")
    target = report.get("target", "")
    severity = report.get("severity", "medium")
    summary = content.get("summary", "") if isinstance(content, dict) else ""

    lines = [
        f"# {title}",
        "",
        f"**Program:** {program}",
        f"**Target:** {target}",
        f"**Severity:** {severity.upper()}",
        f"**Estimated Reward:** ${report.get('estimated_reward', 0):.2f}",
        "",
        "---",
        "",
    ]
    if summary:
        lines.append("## Summary")
        lines.append("")
        lines.append(summary)
        lines.append("")

    if isinstance(content, dict) and "findings" in content:
        lines.append("## Findings")
        lines.append("")
        for f in content["findings"]:
            lines.append(f"### {f.get('title', 'Finding')}")
            lines.append(f"- **Severity:** {f.get('severity', 'medium')}")
            lines.append(f"- **Target:** {f.get('target', '')}")
            desc = f.get("description", "")
            if desc:
                lines.append("")
                lines.append(desc)
            lines.append("")

    lines.append("---")
    lines.append(f"*Generated by Rastro — {datetime.now(timezone.utc).strftime('%Y-%m-%d %H:%M UTC')}*")
    return "\n".join(lines)


def _render_html(report: dict[str, Any]) -> str:
    md = _render_markdown(report)
    import html
    safe_md = html.escape(md)
    return f"""<!DOCTYPE html>
<html lang="en">
<head><meta charset="UTF-8"><title>{html.escape(report.get('vulnerability', 'Report'))}</title>
<style>
  body {{ font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
         max-width: 800px; margin: 40px auto; padding: 0 20px;
         color: #e0e0e0; background: #0d1117; line-height: 1.6; }}
  h1, h2, h3 {{ color: #f0f0f0; }}
  code {{ background: #1a1d29; padding: 2px 6px; border-radius: 4px; font-size: 0.9em; }}
  hr {{ border: none; border-top: 1px solid #2a2e3d; margin: 24px 0; }}
  strong {{ color: #f0f0f0; }}
</style></head>
<body><pre style="white-space:pre-wrap;font-family:inherit;color:#e0e0e0;">{safe_md}</pre></body>
</html>"""


def _render_txt(report: dict[str, Any]) -> str:
    md = _render_markdown(report)
    import re
    text = re.sub(r"\*\*", "", md)
    text = re.sub(r"#+\s*", "", text)
    text = re.sub(r"\* ", "- ", text)
    text = re.sub(r"---+\n?", "", text)
    lines = [line.strip() for line in text.split("\n")]
    return "\n".join(lines)


def _render_pdf(report: dict[str, Any]) -> bytes:
    html = _render_html(report)
    try:
        from weasyprint import HTML
        return HTML(string=html).write_pdf()
    except ImportError:
        logger.warning("weasyprint not available, falling back to HTML")
        return html.encode("utf-8")


FORMAT_RENDERERS = {
    "markdown": _render_markdown,
    "html": _render_html,
    "txt": _render_txt,
    "pdf": _render_pdf,
}


def export_report(report_id: int, fmt: str) -> tuple[str | bytes, str]:
    if fmt not in EXPORT_FORMATS:
        raise ValueError(f"Unsupported format: {fmt}. Choose from: {', '.join(EXPORT_FORMATS)}")

    report = _get_report(report_id)
    if report is None:
        raise ValueError(f"Report {report_id} not found")

    renderer = FORMAT_RENDERERS[fmt]
    result = renderer(report)

    mime_map = {
        "markdown": ("text/markdown", ".md"),
        "html": ("text/html", ".html"),
        "pdf": ("application/pdf", ".pdf"),
        "txt": ("text/plain", ".txt"),
    }
    mime, ext = mime_map[fmt]
    return result, mime


def _get_report_versions(report_id: int) -> list[dict[str, Any]]:
    from database.models import ReportVersion
    session = _get_session()
    try:
        versions = (
            session.query(ReportVersion)
            .filter(ReportVersion.report_id == report_id)
            .order_by(ReportVersion.version.desc())
            .all()
        )
        return [
            {
                "id": v.id,
                "version": v.version,
                "content": json.loads(v.content) if v.content else {},
                "summary": v.summary or "",
                "created_at": v.created_at.isoformat() if v.created_at else "",
            }
            for v in versions
        ]
    finally:
        session.close()


def get_report_versions(report_id: int) -> list[dict[str, Any]]:
    return _get_report_versions(report_id)


def save_report_version(report_id: int, summary: str = "") -> dict[str, Any]:
    from database.models import Report, ReportVersion
    session = _get_session()
    try:
        report = session.query(Report).filter(Report.id == report_id).first()
        if not report:
            raise ValueError(f"Report {report_id} not found")

        existing = (
            session.query(ReportVersion)
            .filter(ReportVersion.report_id == report_id)
            .order_by(ReportVersion.version.desc())
            .first()
        )
        next_version = (existing.version + 1) if existing else 1

        version = ReportVersion(
            report_id=report_id,
            version=next_version,
            content=report.content or "{}",
            summary=summary or f"Version {next_version}",
        )
        session.add(version)
        session.commit()
        session.refresh(version)

        return {
            "id": version.id,
            "version": version.version,
            "summary": version.summary or "",
            "created_at": version.created_at.isoformat() if version.created_at else "",
        }
    except Exception:
        session.rollback()
        raise
    finally:
        session.close()
